ALTER TABLE cards
    ADD COLUMN IF NOT EXISTS masked_pan VARCHAR(32);

ALTER TABLE cards
    ALTER COLUMN type TYPE VARCHAR(20),
    ALTER COLUMN status TYPE VARCHAR(20);

ALTER TABLE cards
    DROP CONSTRAINT IF EXISTS chk_card_type,
    DROP CONSTRAINT IF EXISTS chk_card_status;

ALTER TABLE cards
    ADD CONSTRAINT chk_card_type CHECK (type IN ('DEBIT', 'VIRTUAL', 'PHYSICAL', 'PREPAID')),
    ADD CONSTRAINT chk_card_status CHECK (status IN ('REQUESTED', 'PRODUCING', 'SHIPPED', 'ACTIVE', 'BLOCKED', 'EXPIRED', 'CANCELLED'));
