spring:
  application:
    name: eu-bank-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    com.bank: DEBUG
    org.springframework.security: DEBUG

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 86400000
  card-network:
    base-url: ${CARD_NETWORK_BASE_URL:http://localhost:8072}
    api-key: ${CARD_NETWORK_API_KEY:bank-key-eu-a}
    hmac-secret: ${CARD_NETWORK_HMAC_SECRET:secret-eu-a-hmac}
  eu-payments:
    target-url: ${TARGET_URL:http://localhost:8001}
    sepa-batch-url: ${SEPA_BATCH_URL:http://localhost:8002}
    sepa-instant-url: ${SEPA_INSTANT_URL:http://localhost:8003}
    bank-bic: ${BANK_BIC:BANKDEXX}
    bank-name: ${BANK_NAME:Deutsche Bank}
    initial-liquidity: ${INITIAL_LIQUIDITY:1000000.00}
    webhook-secret: ${WEBHOOK_SECRET:my-secret-key}
    webhook-url: ${WEBHOOK_URL:}
  swift:
    url: ${SWIFT_URL:http://localhost:3000}
    client-id: ${SWIFT_CLIENT_ID:bank-bankdexx}
    client-secret: ${SWIFT_CLIENT_SECRET:secret-bankdexx}
    bank-bic: ${SWIFT_BANK_BIC:BANKDEXX}
    enabled: ${SWIFT_ENABLED:true}
    fee-percent: ${SWIFT_FEE_PERCENT:0.01}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
